import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import {
    QueryProvider,
    AuthProvider,
    SonnerProvider,
} from "@/components/providers";
import { ErrorBoundary } from "@/components/error";

import "./globals.css";

const dmSans = DM_Sans({
    subsets: ["latin"],
    weight: ["300", "400", "500", "700", "800"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                {/* THEME FIX: Prevent FOUC by setting theme before React loads */}
                <script
                    dangerouslySetInnerHTML={{
                        __html: `
(function() {
  try {
    var theme = localStorage.getItem('theme');
    if (theme === 'dark' || (!theme && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
      document.documentElement.classList.add('dark');
    } else {
      document.documentElement.classList.remove('dark');
    }
  } catch (e) {}
})();
                        `,
                    }}
                />
            </head>
            <body className={`${dmSans.className} antialiased`}>
                <ErrorBoundary>
                    <QueryProvider>
                        <AuthProvider>
                            <div className="flex flex-col min-h-screen">
                                <main className="flex-grow">{children}</main>
                            </div>
                            <SonnerProvider />
                        </AuthProvider>
                    </QueryProvider>
                </ErrorBoundary>
            </body>
        </html>
    );
}
