import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import Navbar from "@/components/landing/navbar";

import "./globals.css";
import Footer from "@/components/landing/sections/footer";

const dmSans = DM_Sans({
    subsets: ["latin"],
    weight: ["300", "400", "500", "700", "800"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${dmSans.className} antialiased`}>
                <div className="flex flex-col min-h-screen">
                    <Navbar />
                    <main className="flex-grow">{children}</main>
                    <Footer />
                </div>
            </body>
        </html>
    );
}
